services:
  database:
    image: postgres:latest
    container_name: crud_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=crud_db
    ports:
      - "11111:5432"
    networks:
      - mine

  app:
    build: .
    container_name: lcy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://crud_db:5432/crud_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33333:33333"
    depends_on:
      - database
    networks:
      - mine

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --requirepass your_password
    networks:
      - mine

networks:
  mine:
    driver: bridge
